---
title: Chapter 10. Information and Democracy
bibliography: references.bib
csl: apa.csl
---

## The democratic ideal

Democracy means government by the people. There are two primary forms of democracy: one in which the people participate in policy and decision-making directly through their vote (direct democracy) or indirectly by electing representatives who exercise political power on their behalf (representative democracy). Most democracies today are representative democracies. According to @webster_information_2014-1, four essential elements must be in place for a democracy to exist: regular elections and re-elections, a plurality of political parties, a secret ballot, and the universal right to vote. Then, additional factors can be considered to determine whether a democracy is strong or weak. In other words, we can think of some democratic ideal that can only be imperfectly implemented in society, and we may seek at any point in time to question how near or far we are from that ideal and what can be done to bring us closer to it.

::: callout-tip
## Stop and reflect

Can you think of some factors that can make a democracy stronger or weaker?
:::

In your reflection, you may have identified many factors related to information, which is perhaps not a surprise given that democracy is one of the core values of the information field that we discussed in the [first chapter](https://pmongeon.github.io/information-in-society/ch1.html#roles-values-and-principles) of this book. If you look more closely and think about it, you will likely realize that pretty much all of the field's values relate to or support, in some way, the democratic ideal. Let us dive into it a little bit.

First, the value of **rationality** is strongly connected to the democratic ideal, which is not simply about people deciding but about the ability of the deciding people to use reason or logic to inform their decisions. For this ideal of rationality to be attained, people must be informed to consider all relevant facts and ideas (including views opposing their own). This highlights the importance of another core value of the field, **intellectual freedom**, which is about the rights of people to hold, share and access ideas without restrictions. Indeed, it isn't easy to imagine individual voters as perfectly rational agents if they cannot access all the required information or share it with others. Even if, hypothetically, all the relevant data or information would be made available and thus, in theory, accessible, it does not necessarily mean that everyone in practice can access and process it. This is where another value of the information field comes in: **literacy**. Information literacy, data literacy, and all the other literacies we care about in the field are ways to empower individuals to find, evaluate, process, and use information to improve their lives, fully participate in society, and embody the democratic ideal as rational agents. Finally, while it may not be directly linked to the values of the field, **participation** is a crucial element of a properly functioning democracy since having perfectly rational and well-informed agents serves little purpose if only a handful of them take the time to exercise their right to vote. Suppose we interpret the concept of participation more broadly as being engaged in political discussions (i.e., taking part in the production and consumption of information). In that case, we can say how a lack of it may also hinder access to information and undermine our potential for rationality. Moreover, unbalanced participation, where only some voices are heard, can also hurt the quality of democratically made decisions. This brings another of the field's values into play: **equity, diversity and inclusion** in the access and production of information and the representation of the information (this is the focus of the next chapter).

::: callout-tip
## Stop and reflect

Please think of the past chapters in which we discussed the information economy, the attention economy, and misinformation, and consider how those relate to the democratic ideal and the factors we identified necessary to achieve it.
:::

## The public sphere

The concept of the public sphere, which was developed by Jürgen @habermas1999, can be defined as:

> \[A\]n arena, independent of government while also enjoying autonomy from sectional economic forces, which is dedicated to rational debate (i.e., to debate and discussion which is not 'interested', 'disguised' or 'manipulated') and which is both accessible to entry and open to inspection by the citizenry. It is here, in this public sphere, that public opinion is formed. [@webster_information_2014-1]

The public sphere is not just a single place or a time; it's a concept that encompasses both physical and digital spaces, and it is a combination of all those spaces where conversations, ideas and minds meet. The public sphere is also constantly evolving, and its development is greatly affected by technological advances and our increased reliance on digital modes of information exchange [@mckee2004].

In the short video below, Fred Turner discusses the emergence of a digital utopia that envisions digital technologies as enabling a world of free democratic choices and heightened consciousness that is diverse and free of sexism and racism.

<iframe src="https://player.vimeo.com/video/124476893?h=42bfc2815f&amp;color=ff6600" width="640" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen>

</iframe>

<p><a href="https://vimeo.com/124476893">Fred Turner : l'utopie numérique</a> from <a href="https://vimeo.com/culturemobile">Culture mobile</a> on <a href="https://vimeo.com">Vimeo</a>.</p>

::: callout-tip
## Stop and reflect

What do you think of the vision that Turner describes? Do you also think that this vision may be revived? What would need to happen for this to happen?
:::

@mckee2004 discusses five issues with the public sphere.

1.  It is too **trivialized**; people care more about unimportant news like celebrities' lives than real-world events.

2.  It is too **commercialized**: the media wants to make money, and, in the process, quality suffers.

3.  It's a **spectacle**: the public looks for eye-catching visuals and superficial distractions over meaningful conversations about serious issues.

4.  It's too **fragmented**: national culture falls to the wayside while niche identity groups become more common. People are less interested in the same general information.

5.  It has made citizens **apathetic** to critical public issues: people care less about the important political issues of their country.

There are many obstacles to participation in the public sphere. Many of the obstacles found in the real world also translate directly to online communities. The Internet was meant to make politics more inclusive, allowing more people to voice their opinions. It was meant to allow for equal participation. Instead, the Internet reinforces many of the problems seen in the offline world [@albrecht2006].

## The public library and the public sphere

@widdersheim2016 describes the public sphere as a three-layered social phenomenon, including infrastructure (the physical space), people (who exist within the space) and communication (between the people). When looking at the public sphere through this framework, public libraries are part of the public sphere. Libraries were created under the pretense that information belongs to everyone and should be available to everyone. They provide equal access to information for everyone at no cost so that people may be well-informed and able to participate in public debates [@audunson2019]. They are publicly funded by taxation, but their operations are still separate from political interests [@webster_information_2014-1]. Public libraries also help to encourage democracy by providing a space for people to gather and debate. Friends, neighbours, and strangers gather in the public library, generating social capital. Communities with higher social capital tend to have higher civic participation. On top of providing space, libraries also provide the materials people need to learn and be informed of the issues [@appleton2022].

::: callout-tip
## Stop and reflect

How do you think you, in your future career as an information professional, can work to limit the obstacles to participation for the community you serve?

How do you balance intellectual freedom with advocacy and activism?
:::

## The internet and the public sphere

As we spend more time online, more of the public sphere of information is created online. We interact with our friends, family, neighbours, community members, and more on social media.

::: callout-tip
## Stop and reflect

Consider the prerequisites for the democratic ideal. How do they pertain to social media platforms?
:::

Consider the following excerpt from @york2019:

> While the real-name policy shifts the balance of power from users to platform owners, increasing the costs for bad behaviour, it may be accompanied by another effect: a growing reluctance on the part of users to produce content. Facebook routinely prompts users to post content, recycling past posts as memories ready for reposting and assembling albums commemorating friendships between two users so they have something new to post. Scholar Trebor Scholz points out that platforms like Facebook rely on their users to create content---without user-created content, the sites would have nothing to offer (Scholz 2012). This insight has yet to turn into the workers' rights movement Scholz and others have hoped for. While concerns are sometimes raised that the growth of platforms like Facebook is slowing, user-generated content sites are the most popular and influential sites on the Internet.
>
> According to analytics company Alexa, six of the top ten websites in the United States, in terms of traffic, are built on user-generated content---YouTube, Facebook, Wikipedia, Reddit, eBay, and Twitter---and two others, Google and Yahoo!, are arguably built on indexing user-generated content. At this point, user-generated content sites are not the exception to the rule but the dominant social web model. The beauty of this model for the platforms is that users do almost all of the work. The platform is responsible only for providing a space where a user can publish while the user creates the content. The platform succeeds fiscally if it can make more from advertising on user content than it spends creating and maintaining the space. [@york2019]

::: callout-tip
## Stop and reflect

Do sites relying on user-generated content reflect the democratic ideal? Why or why not?
:::

## Decentralized social media

::: callout-note
## In the news

After multi-billionaire Elon Musk's recent purchase of Twitter, there has been renewed interest among users in the moderation of their social media platforms. Some sought alternatives, including decentralized social media platforms like Mastodon and the Fediverse. If you are unfamiliar with decentralized social media, consider watching the following two-minute video on Mastodon:

<iframe width="560" height="315" src="https://www.youtube.com/embed/IPSbNdBmWKE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>
:::

As social media integrates with more traditional media outlets such as news stations, what does decentralized social media mean to the public sphere? Consider the following article: <https://www.cjr.org/analysis/journalists-want-to-recreate-twitter-on-mastodon-mastodon-is-not-into-it.php>

::: callout-tip
## Pause and reflect

What sort of problems could decentralized social media solve? What problems, if any, does it create?
:::

## Algorithms, automation, and echo-chambers

While human users generate most of the content on social media platforms, that content is not necessarily user-curated. Instead, most social media platforms use algorithms to curate content. While the exact programming of many algorithms is shrouded in secrecy, curation can be determined by what the user has selected to view before, who they follow on social media, or other information gathered from the user. While this can create a tailored experience, it can also create echo chambers, where users will see and share content similar to what they already enjoy and endorse instead of being exposed to diverse information. For example, consider the author and law expert Frank Pasquale's writings on the automation of the public sphere:

> The basic contours of mass media-driven politics and culture remained stable throughout the second half of the twentieth century. But since the mid-1990s, the public sphere has endured yet another structural transformation. Megafirms like Facebook and Google have largely automated the decisions once made by managers and programmers at television networks or editors at newspapers. Automated recommendations are often helpful, aiding audiences as they seek to sort out the blooming, buzzing confusion of topics online. But they are also destabilizing traditional media institutions and circuits of knowledge. [@pasquale2018]

Pasquale also writes about how the anonymity offered by the Internet can influence the public sphere:

> While secrecy has empowered some voices who would otherwise be afraid to speak up, it has also protected trolls, doxers, and other bad actors online who silence others' speech via intimidation. Moreover, online anonymity is of piece with financial anonymity, which has empowered thousands of shell companies to obscure who is funding messages that could sway the public, legislators, and regulators. Everyone is invited to participate, but so too is "everyone" capable of disrupting other communities of interest online via hashtag spamming or trolling---whether by civil society groups, state actors, or miscreants pursuing disruption "for the lulz." [@pasquale2018]

## Activism and social media

As political discourse occurs on social media websites, many political movements or other activist causes find a foothold online. Sociologist and writer Zeynep Tufekci speaks to the challenges and successes of social movements online:

:::: {style="max-width:854px"}
::: {style="position:relative;height:0;padding-bottom:56.25%"}
<iframe src="https://embed.ted.com/talks/lang/en/zeynep_tufekci_online_social_change_easy_to_organize_hard_to_win" width="854" height="480" style="position:absolute;left:0;top:0;width:100%;height:100%" frameborder="0" scrolling="no" allowfullscreen>

</iframe>
:::
::::

<br> @york2019 give the following example of how social media can be successful at initiating social change:

> Social media has emerged as a battleground for human rights defenders because of its value in mobilizing resistance movements and in publicizing otherwise invisible points of view. The 2011 uprisings in the Arab world and beyond demonstrated the mobilizing power of UGC platforms, while their aftermath---from the emergence of new democratic norms in some places to war in others---exhibited UGC platforms' value in the documentation of human rights abuses. In late 2010, a Facebook page emerged in Egypt entitled "We Are All Khaled Said" (in English and in Arabic). Set up to memorialize Khaled Said, a young man killed by police in Alexandria, the page was then used to promote an already-organized set of protests, following in the footsteps of the Tunisian protests that had just effectively deposed the country's autocratic leader of twenty-three years, Zine El Abidine Ben Ali. The page's call to protest went viral among Egyptians, many of whom had previously only used Facebook for ordinary activities and communications, and on January 25, 2011, tens of thousands of people took to the streets in protest. The initial effectiveness of the Egyptian uprising, which deposed long-term autocrat Hosni Mubarak, inspired movements throughout the Arab region and well beyond. Some of those movements, such as that which took hold in Syria in February 2011, sparked violent clashes, leading to civil war. In the case of Syria, social media has been effective both in documenting and sharing human rights abuses, as well as in the dissemination of propaganda. Such content is not immune from the impact of content moderation; Facebook and YouTube have both been accused of contributing to the erasure of evidence from Syria. [@york2019]

::: callout-tip
## Stop and reflect

Have you seen movements of social change originate or propagate in your social media platform of choice or elsewhere online?
:::

## Case study

*With the gang still spread out across Canada, they have scheduled a video call to catch up and chat. It's been a while since they graduated, and their conversation centers on changes in the public sphere and how they understand their evolving roles in Information Management.*

**Dante**: How have you all been? It always feels like too much time passes between these video chats. I wish we all still lived in Halifax, but it's great to have us all together now. We missed you in these calls, Jude!

**Jude**: Hey all, I missed you too. It's nice to see your faces and hear your voices. I want all the updates!

**Wren**: Well, I'll go first because I'm sure you're all dying to hear about the fabulous lifestyle of Wren Reilly. I've been good! I am so busy working at the tech company and volunteering in my spare time, but I am happy. Halifax misses you, Dante!

**Tracy**: That is wonderful to hear, Wren. I love seeing your updates on Instagram. I've also been inordinately busy! My daughter Ava just started grade ten and is enrolled in one too many extracurriculars. And she's struggling with speaking French here in Montreal.

**Dante**: That's a hard age; I wouldn't want to return to being fifteen. I know you've told us Ava is a big Taylor Swift fan! I was scrolling through YouTube in bed last night and watched her speech after she was presented with an honorary doctorate in fine arts at NYU.

**Wren**: I watched that, too! My roommate is a huge Swiftie, so I'm always in tune with what's happening with her. She had me watch her documentary as well.

**Jude**: I also watched it- she's a very eloquent speaker.

**Dante**: What did you think of her speech? I found it interesting when she talked about the issues she has dealt with being in the public sphere, how incredibly hard it was almost to be cancelled online back in 2016. It made me think about your situation with the podcast, Jude.

**Wren**: Some parallels there! In her documentary, Taylor talks about finding it difficult to express herself or her political views due to the fear of being cancelled or polarizing her fans. It must be hard to be famous and constantly worry about what you say, do, or post online for fear of backlash.

**Tracy**: It's not just famous people who worry about those things. The public sphere isn't safe for a lot of people. I haven't told you guys yet, but recently, Ava decided to come out on Instagram. She posted a photo of herself and her girlfriend with a caption about their relationship. She thought she was ready, but people are being awful online. She has strangers and classmates writing hateful comments and sending her mean DMs on her posts.

**Jude**: You are right. When dealing with that podcast situation, I worried about creating more backlash against the LGBTQ+ community. Still, I couldn't continue enabling the spread of hateful messages, so I said I couldn't participate in the show anymore. I'm disappointed to hear that Ava's classmates aren't being supportive, Tracy. I'm glad she has a mom like you!

**Dante**: Oh Tracy! I am so sorry to hear that; Ava is such a sweet girl and doesn't deserve to deal with that. I feel like social media creates so many issues. Strangers shouldn't be able to make people feel so bad. It's so easy for people to say things online that they wouldn't say in person.

**Wren**: Yes, I hope things get better for Ava soon! This makes me think of the debate that some of my colleagues and I have discussed about whether social media improves society. When it was first created, I feel like the idea was that it would create a platform where everyone's opinions could be heard and the democratic value of free speech would thrive. But clearly, this isn't entirely true.

**Tracy**: Oh, it's not true; social media has become diluted with misinformation and created polarization between different groups. Different communities only see similar opinions to their thanks to the algorithms that run these sites, which creates a positive feedback loop, reinforcing people's biases. Look at what happened to Jude... it is so easy to find yourself down a rabbit hole surrounded by viewpoints that are cleverly disguised or drown out any sensible ways of being. He was sucked into helping to distribute the same nonsense, and that's not the Jude we know! Thankfully, he found his way back to his ethics and values with help from his friends.

**Wren**: \*Grinning widely\* and a little of Wren's magic.

**Jude**: You're so right, Tracy; it greatly worries me. I often think about what I can do as an information professional to help change this. Maybe ways that I can educate people about these issues.

**Tracy**: I often feel that way too, Jude. I honestly have been feeling so helpless with Ava's situation. I want her to be safe and happy; right now, she isn't feeling either. I don't think she realized the sort of bigger political sphere she was stepping into by coming out so publicly. I hope that it doesn't affect her in any way in the future.

**Wren**: We are here for you and Ava, Tracy. Please reach out anytime, even if you need to talk. This can't be easy for you as her mother.

**Jude**: I agree! We love you, Tracy.

**Dante**: Hear! Hear!

**Tracy**: Thanks, everyone! You know how to help me feel better. I appreciate the chat and looking forward to catching up again soon!

## Discussion questions

-   How do you think social media has impacted Jude?

-   What is your general opinion about social media? In what ways do you think it supports rational debate, collective thinking, and democracy?

-   Consider how public opinion diversity can be united and divided by information and social media.

-   What do you think is (or could be) the role of information professionals in the public sphere?

-   What is your own experience with social media?

If you are interested in watching Taylor Swift's commencement speech, it can be found here: [NYU's 2022 Commencement Speaker Taylor Swift](https://www.youtube.com/watch?v=OBG50aoUwlI).

## References
