---
title: Chapter 3. Information issues
bibliography: references.bib
csl: apa.csl
---

## Learning objectives

This chapter briefly introduces the themes we will explore in more depth in the rest of the textbook. More specifically, it introduces the concept of the information society and describes four fundamental types of information issues we deal with in our individual, professional and social lives.

## The information society

The information society is [a band from the 1980s](https://www.youtube.com/watch?v=ijAYN9zVnwg&ab_channel=infosocietyVEVO), but it is also a type of society that succeeds the industrial society and in which information plays a dominant role. Theorists of the information society have focused on five dimensions of the information society [@webster_definitions_2014]:

The **technological** dimension of the information society is reflected in the growth of information technologies such as personal computers, smartphones, and the internet, which are now ubiquitous. The **economic** dimension of the information society emphasizes the dominance of information and knowledge industries and the increased share of countries' GDP they generate. The rise of service industries demonstrates the occupational dimension and highlights that in information societies, most employees are not involved in producing tangible goods. The **spatio-temporal** dimension of the information society is centred around networks, digital technologies, and hyper-connectivity that transcend some of the time and space constraints of the physical world. Think, for example, of how information technologies allow you to engage with groups distributed around the globe or attend a live event in Australia or Norway no matter where you are. Think of how, in the middle of the night, you can virtually be somewhere where it is the middle of the day. The **cultural** dimension of the information society points to the role of information in the production and reproduction of culture and individual and collective identities. Finally, the **theoretical knowledge** dimension emphasizes the rise of evidence-based practice and the centrality of data, information and knowledge as the increasingly dominant drivers of individual and collective action.

These dimensions are not independent and are all intertwined, so it can be challenging to consider one without the others. Still, they allow us to consider our world and the kind of problems we are dealing with from different angles. This can help us achieve a more holistic perspective on information and its role in society and perhaps better solutions to the information problems we will tackle as information professionals.

::: callout-note
## Suggested reading

Despite being a little bit dated and not written for an information science audience, the following book (which used to be the foundation of the course) can be a helpful resource if you are interested in getting an overview of the main theories of the information societies that have been proposed by scholars over the last 50 years or so.

Webster, F. (2014). *Theories of the Information Society* (4th ed.). Routledge. <https://doi.org/10.4324/9781315867854>
:::

## Types of information issues

In the previous chapter and class, we explored the concept of information. We situated it in relation to dozens of related concepts, which I hope helped you expand your understanding of how information manifests itself in the different spheres of society. No matter where we look in this complex conceptual landscape, we can find opportunities and challenges for information professionals, or let's call them "information issues" for us to tackle. I would argue that there are four fundamental forms of information issues:

-   Issues of information **access**

-   Issues of information **quantity**

-   Issues of information **quality**

-   Issues of information **behaviour**

Some of these will come back in one way or another in the following chapters, so the goal is to provide a high-level overview and introduce some topics we will dive more deeply into later on.

### Access issues

Article 19 of the 1948 Universal Declaration of Human Rights states that "Everyone has the right to freedom of opinion and expression; this right includes freedom to hold opinions without interference and to seek, receive and impart information and ideas through any media and regardless of frontiers". Also, Article 27.1 states that "Everyone has the right freely to participate in the cultural life of the community, to enjoy the arts and to share in scientific advancement and its benefits". These two points are closely tied to several of the core values of the field presented in Chapter 1, such as stewardship and intellectual freedom. The term **participate** in Article 27.1 can be related to access in terms of having access to the means of production and dissemination of information (e.g., computer, smartphone, internet).

Despite being considered a universal human right, there are still many ways in which access to information is limited today. Some constraints can be **physical** when information is recorded on a non-digital medium and stored in a specific location, which may or may not be easily accessed, or when digital information resources are behind a paywall. Access to information is at the core of the mission of libraries that build collections of physical and digital information resources so the communities they serve can access them. This also applies to other settings in which information professionals work; there is often (if not always) an information user with more or less explicit and clearly defined information needs and an information professional whose role may be to ensure that the user has access to the information they need to fulfill those information needs.

::: callout-tip
## Pause and reflect

Do you think that all information should be accessible to everyone? If not, what kind of information do you think should not be accessible to all? How can you reconcile the notion that some information should not be accessible to all with the idea of information as a human right?
:::

Another critical issue to consider is the **inequalities** in access to information. Since information is crucial for personal, social and professional development and for people to thrive in the information society, differences in access to information based on socio-demographic factors can contribute to creating or reinforcing existing inequalities. That is one of the reasons why equity, diversity, and inclusion are important topics in our field and why you hear about them in many of your courses.

The unequal access to information is often referred to as the **digital divide**, defined as "the gap between individuals, households, business and geographic areas at different socioeconomic levels with regard both to their opportunities to access information and communication technologies and to their use of the internet for a wide variety of activities" (OECD, 2001). You can check out the network readiness index (<https://networkreadinessindex.org/>) to see how countries are doing regarding digital infrastructures, connectivity and governance. Even within a single country, demographic factors can have a strong relationship with physical access to information and information technology. Income, age, gender, education and location are all predictors of whether people have internet access. And varying levels of information literacy may lead members of some social groups not to access information even when it is available [@sparks_what_2013].

Access is also closely linked to the **literacy** concepts family (information literacy, data literacy, digital literacy, etc.), which is core to the information professions, especially in public and academic librarianship. That is where language and the ability to read and write come in, as one cannot access information if it is in a language they do not understand or if it is in a written format and they don't know how to read. Similarly, people cannot participate in the information society if they don't have the basic ability to communicate. Teaching people how to read, write and use information technologies is not typically understood as the role of information professionals. However, public libraries are often used as community centers where such training can occur.

::: callout-tip
## Pause and reflect

-   In what ways do you think technologies help solve information access issues?

-   In what ways do you think technologies do not help, or even accentuate, information access issues?

-   How do you think information professionals can play a role in ensuring that technologies effectively increase access to information?
:::

### Quantity issues

There is a lot of information in the world, and a lot of new information is produced every day (that is, of course, if you subscribe to the notion of information as a thing. Otherwise, we could rephrase this and say that there is a lot of information happening every day). The following two quotes can help us grasp just how much information we are talking about.

> *The amount of information being created every two days is equivalent to that created from the dawn of civilization until the year 2003* [@benselin_information_2016].

> "A weekly edition of the New York Times contains more information than the average person was likely to come across in a lifetime in seventeenth-century England" [@bawden_dark_2009].

Living in a world of **information abundance**, it may be difficult to imagine that we could still find ourselves in situations of **information scarcity**. Isn't finding the information we need as simple as picking up our smartphones and "googling" whatever we want to know?

::: callout-tip
## Pause and reflect

Can you think of a situation in which you found yourself not finding (or having a lot of difficulty finding) the information that you needed? How did you feel? How did you cope with the situation? What was the outcome?
:::

You may think that the general abundance of information is a good thing. After all, isn't information the basis of all (or most) knowledge and better "informed" decisions? Can there be too much of a good thing as information?

::: callout-tip
## Pause and reflect

Can you imagine a situation where you found yourself having too much information? What was the context? How did you feel? How did you cope with the situation? What was the outcome?
:::

The idea that there is a point where more information is just too much information is often called **information overload.** This is by no means a new phenomenon, but as technological developments increase our capacity to produce, disseminate and store information, so does the amount of information that the average human is exposed to and needs (or believes they need) to process or manage. When the amount of information exceeds our capacity for processing and managing it, we are in a situation of information overload [@misra_psychological_2012]. Information overload can cause many adverse outcomes, including psychological stress, exhaustion, negative affect, decreased productivity [@matthes_too_2020], information addiction, distraction, and symptoms similar to attention deficit disorder [@bawden_dark_2009].

The following video is about how having too much choice leads to poorer decisions or less satisfaction about our decisions, which the speaker calls the "paradox of choice". I think it also applies to information and that we have, in fact, a "paradox of information".

:::: {style="max-width:854px"}
::: {style="position:relative;height:0;padding-bottom:56.25%"}
<iframe src="https://embed.ted.com/talks/lang/en/barry_schwartz_the_paradox_of_choice" width="854" height="480" style="position:absolute;left:0;top:0;width:100%;height:100%" frameborder="0" scrolling="no" allowfullscreen>

</iframe>
:::
::::

<br><br>

### Quality issues

Access to information is great, and access to a lot of information is even better (with some caveats, as discussed above). However, another fundamental concern with our information society is the quality of the information available to us. Again, if information is the basis of all (or most) knowledge and better "informed" decisions, what happens if the information we receive is inaccurate or simply false? We may reject that information by using our filtering mechanisms or critical thinking skills. In this case, the cost is some time for the filtering and selecting process. But what if we do not assess information, fail to recognize its poor quality and use it as a basis to form an important decision or to shape our worldview?

The widespread presence and spread of **misinformation** (and related concepts such as disinformation and fake news) has been facilitated by the rise of the internet and other information technologies that make the production and dissemination of information accessible to all. @bran_learning_2021 used the term Information pollution or 'infollution' to describe the growing problem of the spread of unwanted messages in society in quantity large enough to affect human and social activities significantly, and consider conspiracy theories, propaganda, memes and memetic warfare, and ideological manipulation as forms of infollution that can result in wasted time, physical and mental health issues and stress or addiction. No matter how one calls it or in what shape or form it presents itself, misinformation is one of the [greatest challenges of our age](https://www.bbc.com/future/article/20170301-lies-propaganda-and-fake-news-a-grand-challenge-of-our-age).

There are other ways to think about information quality that come short of falling under the "misinformation" label. For example, we may consider that information is of poor quality when it is, for one reason or another, ineffective in achieving the desired goal (e.g., to inform, to increase knowledge, to make a decision). It may also be helpful to think about information not only in terms of a single information unit (e.g., a news article or a single statement in a text) but also in terms of collections of information units (e.g., a library collection, a set of resources used to support a decision).

::: callout-tip
## Pause and reflect

Can you think of ways valid and accurate information may be ineffective at fulfilling an information need or supporting a decision or action?
:::

Information issues can lead to **Information anxiety,** defined as the state "produced by the ever-widening gap between what we understand and think we should understand. It is the black hole between data and knowledge, and it happens when information doesn't tell us what we want or need to know" [@naveed_towards_2020, p. 66]. Its symptoms may include the inability to keep up with the information we are presented, frustration over the quality of information available, guilt about not being better informed, or the desire to be the first to know.

### Behaviour issues

So far, we have mainly discussed issues related to the information itself and its accessibility, quantity and quality. However, the last fundamental form of information relates not to the information itself and its characteristics but to how we use it or interact with it: our **information behaviour**.

Suppose we side with @hjorland_information_2007 and consider that only the subjective/situational concept of information is helpful for information professionals. Then, we must conclude that all information phenomena that information professionals care about involve humans (or computers) that seek, evaluate, filter, store, organize, produce, disseminate, share, use, or react to information in their own way, depending on the context. In that case, the information world we live in (and all its issues of access, quantity, and quality) is the product of individual or group behaviour. However, our information behaviour has effects that transcend the informational world and can positively or negatively affect our individual and collective lives.

::: callout-tip
## Pause and reflect

Can you think of three examples of information behaviour that can have a positive impact on our lives or the lives of others?

Can you think of three examples of information behaviour that can have a negative impact on our lives or the lives of others?
:::

The notion of **intent** is important to consider when thinking about information and the outcomes of our information behaviour. For example, a corporation may intentionally reduce access to information by creating a paywall around highly valuable information. We may produce and disseminate a lot (quantity) of free content (access) with catchy titles but a low informative value (quality) to attract readers (behaviour) and generate ad revenues (intent). A social media user may intentionally post information (true or false) about someone else to hurt them. We may intentionally or unintentionally produce or share misinformation. Finally, we may intend to fulfill an information need by gathering a lot of information resources. Still, we end up causing information overload, analysis paralysis, or anxiety for ourselves or our users or clients.

## Questions for reflection

1.  What do you think information professionals can do to address the issues related to information access, quantity, quality, and behaviour?
2.  Think about your own information behaviour. Do you think that there are things you could do to interact better with information and live a healthier, informational life?

## Case study

Over the next nine weeks, we will follow four classmates and friends as they navigate graduate school and work in the information field. These characters will deal with many scenarios in which information affects their daily lives, giving you a chance to offer classmates advice and consider how you might deal with similar situations.

### The characters

**Wren Reilly (she/her)** is a 28-year-old from Collingwood, a small town in Ontario. Wren is an aspiring data manager hoping to work in a position that allows her to work independently and utilize her organizational skills. Wren hopes that her undergraduate degree in computer science from the University of Toronto will lend itself well to her future career in data management. She is logical, individualistic, and introverted and works well under pressure. Wren worked for a couple of small new businesses throughout her 20s, helping with programming, and worked in tech support for a larger organization. She plans to work with an organization one day where she can use the knowledge she will gain of databases to deal with big data.

**Dante de Luca (he/they)** is a 24-year-old aspiring public librarian from Calgary, Alberta. Dante has an undergraduate degree in Psychology from the University of Calgary. They considered a career in social work before realizing that public librarianship would allow them to combine their love of helping others with their desire to engage with the community. Dante has always had a passion for libraries. They grew up going to their local library every Saturday with their mom. Throughout high school, they volunteered as a reading buddy for younger children. During their undergraduate degree, they volunteered with newcomers through the English language learning programs at the Calgary Central Library. In the years before deciding to return to school to pursue a graduate degree, Dante worked as a front desk administrator at a dog sled tour company in Canmore, Alberta. Dante is an extroverted and caring individual with leadership qualities and aims to one day be the chief executive librarian of a system of libraries.

**Jude Jamieson (he/him)** is a 31-year-old originally from Cape Breton, Nova Scotia. Jude has an undergraduate degree in History from Acadia University. He spent his twenties trying to decide what direction he wanted his career to go. He has worn many hats, including baker, server and research assistant. Ultimately, he decided to pursue further education to work as an archivist. He feels his love of history and research will suit this profession well. Jude has utilized the archives in the past, working with the archivist at Acadia when he was writing his undergraduate thesis. He loves organizing and working with the artifacts that make up our past. Jude is an introverted, thoughtful and nostalgic individual and would love to work as a digital archivist.

**Tracy Mina Brown (she/they)** is a 40-year-old who grew up in Amsterdam in the Netherlands. Tracy received a Bachelor of Fine Arts from the University of Amsterdam. Before applying for the MI program, Tracy worked as a professional in a non-profit organization and as a digital content manager. Her job requires this sort of confident, extroverted, team-player visage, which she does well, but then she needs and enjoys the quiet and focus of just doing the work alone. She enjoys being highly focused and sees this as a strength. Tracy is pursuing a career in knowledge management, preferably with a non-profit in the arts.

### Setting

You, Wren, Dante, Jude and Tracy have all just started your first year as Master of Information Students at Dalhousie University. You met during the orientation process put on by the university. While sitting on the patio at a pub down by the waterfront, you discuss what led you to the information profession or back to school.

You all sit down and order your food and drinks. You are curious and ask the others: What brought you to the MI program?

**Jude**: Well, my undergraduate degree was in history and focused on a Nova Scotian context. When I finished my degree, I worked as a baker for a few years, but I kept picking up side projects with the local archives in my town, transcribing documents online and digitizing my family's cookbooks. After a while, I figured that if this was something I was interested in, I should pursue it as a career!

**Dante**: That's so cool how you took your interests and turned them into career passions! I've always loved to read, and I've dreamed of opening a bookstore and coffee shop for years. I ended up going to school for psychology and business but realized along the way that opening a business wasn't for me. I talked to a family friend who works as a librarian, and it seemed the perfect fit. I would still get to work with books and people but without the stress of keeping a business afloat. I want to make the world a better place, and I think libraries can help make that possible. Creating a space where people of all backgrounds can gather and where information and knowledge are free is so important! I know that to become a librarian, I'll need the ALA accreditation, which affected my decision to apply to Dalhousie.

**Jude**: I also thought the ALA accreditation would be significant to have as an archivist. Looking over the competencies developed through this degree, it seemed that they would all be directly relevant to the skills I would need to succeed in my career.

**Wren**: I'm interested in the technology part of the program, and my goal is to land a data science position in a tech firm and then move up to a management role. I have a background in computer science, and what attracted me to the program is that it brings together technology, management, information, and people in a way that will be more beneficial for me than the computer science programs, which are very focused on technology.

**Tracy**: I came here after a career in non-profits. I have a fine arts degree; if you're not a gallery or corporate artist, you work in non-profits. But I wasn't formally trained to deal with an organization's challenges. I mean, I can creatively problem solve, which they seem to appreciate, but honestly, just as much fails as often as it works, and I don't even know why. So, while I really like the non-profit I was with and think their cause is amazing, I returned to school because I felt like every day I was just winging it. Knowing how things should and can work would be nice, rather than hoping they work!

**Wren**: That's a good reason to apply to school, Tracy! Say, did our order get put through? I guess they forgot; it's been like 45 minutes!

**Dante**: Ya, but look how busy it is here. The servers are run off their feet; I bet their communication is not ideal with this much going on.

Looking around, they recognize the importance of information flows in this restaurant and all kinds of businesses. They realize that they have all experienced related issues in their previous careers.

**Dante**: I totally understand what it's like to have issues with informational flow. When I worked at a dog sled tour company, there were always issues with the communication between the front desk staff and the customers. There was a tight cancellation policy, and if it was not understood properly, customers would end up paying for tours they couldn't attend, and boy, that made them angry! No one wants to feel like they've wasted \$400!

**Wren**: Jeez, I bet that caused a lot of headaches for the front desk! What did you think could have been done better to avoid those issues?

**Dante**: I think if we had a database and computer system that would keep track of our clients and bookings and send out automated confirmation emails, there would be a lot less room for human error and a better flow of communication! I found that the owners weren't too open to my suggestions, so I made a point of returning to school to bring my ideas to a new organization!

**Jude**: Yeah, that's a really good reason to quit! I worked as a baker and often dealt with supply chain issues. It wasn't always appropriately communicated what was and wasn't available, so it was hard to plan our menu. Customers weren't always happy when we couldn't have their favourite baked goods available, but we tried our best!

**Tracy**: People can be really grumpy in the morning before their morning cup and bagel, that's for sure! When I worked at the non-profit, we spent a lot of time applying for grants and often found that the instructions for what was expected were not clear. This made it so hard to gain the funding we required. Every time I wrote one for our organization, I felt like I was making this stuff up, as I never really knew what people were working on in our organization or what projects they wanted to get done. Also, we were all over the place with people in countries around the globe -- it was impossible to meet them all, let alone know what their ambitions were.

**Wren**: Wow, I never really thought about how lack of communication or misunderstandings can affect how so many businesses are run. I worked on several coding projects during my undergrad, and different people worked on the same code. Sometimes, that would be a mess when we didn't have a shared understanding of the project's goal or when people didn't document their changes properly. That can get very inefficient and frustrating!

You have been sitting back and listening to the conversation between your new classmates. Consider the following questions relating to the conversation.

### Discussion Questions

1.  What are 1-2 benefits you think Jude will get from the MI program?
2.  What 1-2 benefits do you think Tracy will get from the MI program?
3.  Consider the benefits you provided for each Jude and Tracy. Were they the same? If not, how would you explain the differences?
4.  Examine the MI course offerings to propose a set of elective MI courses for Dante -- explain your choices.
5.  What are 1 or 2 information problems you have experienced in your life up to now? How did you handle these issues?

## References
