project:
  type: book

book:
  title: "Information in Society"
  author: "Philippe Mongeon"
  date: "2022-08-26"
  chapters:
    - index.qmd
    - ch1.qmd
    - ch2.qmd
    - ch3.qmd
    - ch4.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



