# What is information?

## Introduction

The purpose of this introductory chapter is to provide an overview of the very diverse range of professional pathways of which your ALA-accredited information management program can lead you. As we will see in this chapter, information management degrees are about a lot more than librarianship and can provide you with many opportunities. Whether you're interested in libraries, archives, museums or even working as an information manager in a corporation, this chapter will give you an overview of jobs available, the skills you'll need and what professional values are important for success.

### Learning objectives

-   To give an overview of careers in the information field

-   To give a background on the profession including some of the skills required and the job possibilities

-   To show what the core values of the information profession are

-   To provide real-world examples through interviews with information professionals

### What are the information professions?

## Discussion questions

1.  Does good data necessarily lead to good information?
2.  Is information subjective or objective, or both?
3.  If two people read the same book, will they receive the same information?
4.  If you read the same book twice, do you receive the same information?
5.  When is a submarine a document?
6.  Does all information transfer require language?

## Suggested readings

@bates2008

---
nocite: |
bibliography: references.bib
---

## References

::: {#refs}
:::
