---
title: "Assignment #0 - Participation" 
---

# Part 1 - Engagement plan

You embarked on the information in society journey with some expectations and goals for yourself. Take a moment to reflect on those and put them on paper, so that you can later refer to them to check in on yourself and see how well you are doing relative to your own expectations.

## To submit on Brightspace

A text of no more than 300 words (can be bullet points) establishing some engagement goals for yourself.  You may wish to provide some context (e.g., “Asking a question in class is not something I usually do, and it would require me stepping out of my comfort zone”). Here are some questions to help you think about this (you don’t have to answer them all or at all):

-   Do you intend to attend all the classes?
-   Do you intend to do the readings ahead of classes?
-   There are reflection questions throughout the chapters. Do you intend to take the time to think about them?
-   What are your expectations with assignments? Do you want to just get them done and move on? Or do you want to challenge yourself a little? How much time and effort are you hoping to put into them?

# Part 2 - Midterm Check-in

Midway through the semester, take a moment to check in with yourself and see how well you are doing so far and what you may want to improve for the second half of the semester.

## To Submit on Brightspace

A text of no more than 300 words commenting on your engagement in the course so far, based on the goals you set for yourself in your engagement plan. You may wish to establish new goals for the second half of the semester or comment on how you want to improve or maintain your engagement.

# Part 3 - Engagement Self-Assessment

As the course and the semester are about to end, take a moment to look back at your information in society course and how much you engaged with the topic covered in the course, the material and your colleagues.

## Submit to Brightspace

A text of no more than 300 words commenting on your level of participation in the course. You may indicate in the text what letter grade you would give yourself, but this is not required. Here are a few elements you *may* wish to consider, along with the engagement goals you set for yourself at the beginning of the semester:

-   **Attendance**: How many classes did you attend?
-   **Preparation**: Did you read some of the materials and came to class prepared?
-   **Engagement**: Did you actively engage in discussions in or with your instructor or TA?
-   **Effort**: How happy are you with your assignments? Did you put in as much effort as you would have expected or hoped for yourself?
