---
title: Assignment 1 - Analysis of an Information Setting
---

# Context

Since joining the Information in Society course, you have started to observe the world around you from an information perspective, and you are beginning to see information phenomena everywhere and all the time. You see it in your sleep, and you see it in your cereal… everywhere. It’s like a superpower. So you decide to practice this new superpower by taking a moment to analyze the information phenomena that occur in a specific setting.

# Instructions

Choose a physical, virtual, or hybrid setting where information phenomena are occurring. You can be creative and choose a setting where information is not the first thing that comes to mind (e.g., an emergency room or a game of Monopoly). It can also be a personal space (e.g., your kitchen or home office). Avoid choosing a setting that is too large to be fully observed (e.g., Dalhousie University in Halifax or the internet). Please reach out to me if you can’t find a setting or would like to discuss your choice.

# To Submit on Brightspace

An approximately 1,500-word text including:

1.  A brief description of the setting.
2.  The type(s) of data/information/knowledge are at play in the setting.
3.  The function(s) of information in the setting.
4.  The interactions between people and information in the setting.
5.  The factors that facilitate or hinder the information processes (e.g., use, access, exchange, etc.) in the setting.
6.  The impact of technologies on the setting.
7.  The implications/opportunities for information professionals.

::: callout-tip
## Note

You don’t have to include all of the elements listed above in your paper if some are not relevant for the specific setting you chose. If that is the case, please provide a short explanation in your paper. Likewise, if you wish to include additional sections to your paper, please feel free to do so but briefly justify your decision.
:::

# Grading Criteria

-   The analysis is clear, logical and sufficiently detailed (15 points)
-   All elements are included, and exclusions/additions are justified (10 points)
-   Adequate length of the paper (2.5 points)
-   Quality of writing (absence of typos, etc.) (2.5 points)
