---
title: "Assignment #3 ­– Essay"
---

## Context

Your ideas continued to evolve as you progressed through more of the readings and discussions in your information in society course, and you decided that it was now time to finalize the essay and put those brilliant ideas into the world (or at least in the hands of your instructor). So you head to a good writing spot, put on your favourite music, and start writing…

## Instructions

Write an expository or argumentative essay of about 4,000 words on a topic of your choice that relates to the course. I recommend using the following structure for your essay:

1.  Introduction
2.  Background/context
3.  Objective(s) of the essay
4.  A brief outline of the essay
5.  Body
6.  Include an adequately titled subsection for each key point of your essay.
7.  Conclusion
8.  Summary of key points
9.  General conclusion
10. Broader implication or future action

**Notes:**

-   Sources of various types (e.g., peer-reviewed scholarly articles, opinion pieces, videos) may be suitable but should be evaluated for their quality, authoritativeness, and relevance.
-   There is no minimum (or maximum) number of references to include.

## Submit on Brightspace

-   Your essay.

## Evaluation criteria

-   Strength of the argument or exposé.
-   Structure, quality and flow of the text.
